config/routes.rb
Rails.application.routes.draw do
root 'static_pages#home'

  get 'sign_up', to: 'users#new'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :name, presence: true, length: {minimum: 6, maximum: 50}
	validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 6, maximum: 255}, format: {with: VALID_EMAIL_REGEX }
	before_save {email.downcase!}
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
  	render html: "Test"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = 'Sample App'
		if page_title.empty?
			base_title
		else
			page_title + '|' + base_title
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The <a href="http://www.railstutor.org/">Ruby on Rails Tutorial</a>
		by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
	</small>
	  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  	<div class="container">
	  	<%= link_to("My Sample App", root_path , id: "logo") %>
	  	<nav>
			  <ul class="nav navbar-nav navbar-right">
			  	<li> <%= link_to("Home", root_path) %></li>
			  	<li> <%= link_to("Help", help_path) %></li>
			  	<li> <%= link_to("Log in", "#") %></li>
		  	</ul>
		  </nav>
		</div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header'%>
  <div class="container">
  	<%= yield %>
  </div>
  <%= render 'layouts/footer'  %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>About page .</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>Contact page..</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>get help..</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
	<h4>Welcome to the Sample App</h4>
	<h5>
		This is the home page for my tutorial practice with <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>..
	</h5>
	<%= link_to("Sign up now!", sign_up_path , class: "btn btn-primary btn-large") %>
	<%= image_tag("kitten.jpg", alt: "Kitten pic")%>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h4>Sign Up Page</h4>
<h6>Sign Up form..</h6>